name: Join Workflow Example
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Build the project
        run: echo "Building the project..."
 
  test:
    runs-on: ubuntu-latest
    needs: build  # This job will only run after the 'build' job is successful
    steps:
      - name: Run tests
        run: echo "Running tests..."
 
  lint:
    runs-on: ubuntu-latest
    needs: build  # This job also depends on 'build'
    steps:
      - name: Lint the code
        run: echo "Linting the code..."
 
  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]  # This job will run only after both 'test' and 'lint' succeed
    steps:
      - name: Deploy the application
        run: echo "Deploying the application..."
