name: JSON Example Workflow
 
on:
  push:
    branches: [ main ]
 
jobs:
  json-processing:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
 
      - name: Install dependencies
        run: npm install
 
      - name: Run JSON processing script
        run: node scripts/processData.js
