name: Node.js Setup & Code Formatter
 
# Trigger the workflow on push and pull request events
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  format:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
 
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4
 
      # Step 2: Set Up Node.js Environment
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Specify Node.js version
          cache: 'npm'        # Cache node_modules to speed up builds
 
      # Step 3: Install Project Dependencies
      - name: Install Dependencies
        run: npm install  # Install all npm dependencies, including Prettier
 
      # Step 4: Check Code Formatting Using Prettier
      - name: Check Code Formatting
        run: npx prettier --check .  # Validate code formatting
 
      # Step 5: Auto-fix Formatting Issues If Found
      - name: Auto-Fix Formatting Issues
        if: failure()  # Only run if the previous step (check) fails
        run: npx prettier --write .  # Automatically fix formatting issues
 
      # Step 6: Commit and Push Changes (If Any)
      - name: Commit & Push Changes
        if: success() && github.event_name == 'push'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: auto-format code via GitHub Actions" || echo "No changes to commit"
          git push
 
